updated protoc wrapper fro better grpc support

diff --git a/protoc-wrapper b/protoc-wrapper
--- a/protoc-wrapper
+++ b/protoc-wrapper
@@ -1,53 +1,55 @@
 #!/usr/bin/env bash
-c_out=""
-csharp_out=""
-includes=()
-outs=()
-args=()
+function usage() {
+    echo ""
+    echo "Used to generate protoc files for a known language, and to generate grpc"
+    echo "files easily"
+    echo ""
+    echo "  required arguments:"
+    echo "    --language    the language to generate in grpc, can be a csv"
+    echo ""
+    echo "  optional arguments:"
+    echo "    --grpc        If grpc files should be included for the language"
+}
 
-for arg in $@; do
-    case $arg in
-        --c_out=*)
-            c_out=${arg}
-            shift
-            ;;
-        --csharp_out=*)
-            csharp_out=${arg}
-            shift
-            ;;
-        --grpc-csharp_out=*)
-            csharp_out=${arg}
-            shift
-            ;;
-        --*_out=*)
-            outs+=(${arg})
-            shift
-            ;;
-        -I*|--proto_path=*)
-            includes+=(${arg})
-            shift
-            ;;
-        *)
-            args+=(${arg})
-            ;;
-    esac
+langs=""
+grpc=""
+
+while [ $# ];do case $1 in
+    --language) langs="${2}"; shift ;;
+    --grpc) grpc="true";;
+    --help) usage; exit 0 ;;
+    *) break ;;
+esac; shift; done
+
+echo ${langs}
+if [[ -z ${langs} ]]; then
+    echo "Missing required parameter: --language"
+    usage
+    exit 1
+fi
+
+set -eu
+cmd="protoc "
+for lang in $(echo "${langs}" | tr ',' ' '); do
+    echo "processing lang=${lang}"
+    cmd="${cmd} --${lang}_out=."
+    if [[ ${grpc} ]]; then
+        echo "adding grpc flag for ${lang}"
+        cmd="${cmd} --grpc_out=. --plugin=protoc-gen-grpc=/usr/bin/grpc_${lang}_plugin "
+    fi
+    echo "using cmd=${cmd}"
+    proto=""
+    for proto in $(find . -name \*.proto -print); do
+        echo "running for ${proto} file"
+        eval "${cmd} --proto_path=. ${proto}"
+        echo "finished ${proto} file"
+    done
+    if [[ -z "${proto}" ]]; then
+        echo "no .proto files found in working directory!"
+        exit 1
+    fi
+    echo "finished processing for ${lang}"
 done
+echo "all finished"
 
-if [ ${#includes[@]} -eq 0 ]; then
-    # replicate protoc behavior
-    includes+=("-I.")
-fi
 
-protoc_cmd="protoc ${includes[@]} ${outs[@]} ${args[@]}"
-protoc_c_cmd="protoc-c ${includes[@]} ${c_out} ${args[@]}"
-protoc_csharp_cmd="protoc-csharp ${includes[@]} ${csharp_out} ${args[@]}"
-
-if [ ${c_out} ]; then
-    ${protoc_c_cmd} || exit 1
-fi
-if [ ${csharp_out} ]; then
-    ${protoc_csharp_cmd} || exit 1
-fi
-if [ ${#outs[@]} -gt 0 ]; then
-    exec ${protoc_cmd}
-fi
